USE [master]
GO
/****** Object:  Database [SGDEMO]    Script Date: 04-Jul-25 5:57:38 PM ******/
CREATE DATABASE [SGDEMO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SGDEMO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\SGDEMO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SGDEMO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\SGDEMO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SGDEMO] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SGDEMO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SGDEMO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SGDEMO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SGDEMO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SGDEMO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SGDEMO] SET ARITHABORT OFF 
GO
ALTER DATABASE [SGDEMO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SGDEMO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SGDEMO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SGDEMO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SGDEMO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SGDEMO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SGDEMO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SGDEMO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SGDEMO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SGDEMO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SGDEMO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SGDEMO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SGDEMO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SGDEMO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SGDEMO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SGDEMO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SGDEMO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SGDEMO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SGDEMO] SET  MULTI_USER 
GO
ALTER DATABASE [SGDEMO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SGDEMO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SGDEMO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SGDEMO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SGDEMO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SGDEMO] SET QUERY_STORE = OFF
GO
USE [SGDEMO]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [SGDEMO]
GO
/****** Object:  User [sgadmin]    Script Date: 04-Jul-25 5:57:38 PM ******/
CREATE USER [sgadmin] FOR LOGIN [sgadmin] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [sgadmin]
GO
/****** Object:  Table [dbo].[GuestInfo]    Script Date: 04-Jul-25 5:57:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GuestInfo](
	[GuestName] [nvarchar](50) NULL,
	[MobileNumber] [nchar](10) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SG_AdvanceReservations]    Script Date: 04-Jul-25 5:57:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SG_AdvanceReservations](
	[TransactionID] [int] IDENTITY(24000,1) NOT NULL,
	[ReservationCode] [varchar](10) NULL,
	[FullName] [nvarchar](100) NULL,
	[MobileNumber] [varchar](15) NULL,
	[EmailAddress] [varchar](100) NULL,
	[Address] [nvarchar](200) NULL,
	[CompanyName] [nvarchar](100) NULL,
	[ReservationDate] [datetime] NULL,
	[AdvanceAmount] [decimal](10, 2) NULL,
	[FunctionType] [nvarchar](100) NULL,
	[FunctionDate] [date] NULL,
	[CheckNumber] [varchar](50) NULL,
	[CheckTotal] [decimal](10, 2) NULL,
	[CheckOpenTime] [datetime] NULL,
	[CheckClosedTime] [datetime] NULL,
	[TaxAmount] [decimal](10, 2) NULL,
	[ServiceCharge] [decimal](10, 2) NULL,
	[DiscountAmount] [decimal](10, 2) NULL,
	[SubTotal] [decimal](10, 2) NULL,
	[Notes] [nvarchar](max) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ReservationCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SG_AdvanceReservations] ADD  DEFAULT (getdate()) FOR [ReservationDate]
GO
ALTER TABLE [dbo].[SG_AdvanceReservations] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
USE [master]
GO
ALTER DATABASE [SGDEMO] SET  READ_WRITE 
GO
